version: '3.8'

services:
  localstack:
    container_name: drive_clon_localstack
    image: localstack/localstack:4.4.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "localstack_data:/var/lib/localstack"

  app:
    container_name: drive_clon_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_S3_BUCKET=drive-clon-bucket
      - NODE_ENV=development
    depends_on:
      - localstack

volumes:
  localstack_data:
